[package]
name = "app"
version = "0.1.0"
edition = "2021"
description = "Annoter f***** javascript package manager"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "1.3"
